[pytest]
# Point Pytest to the main Django settings file
DJANGO_SETTINGS_MODULE = config.settings

# Tell Pytest how to recognize test files
python_files = tests.py test_*.py *_tests.py

# Default command line options for Pytest
# --nomigrations: Speeds up tests by creating the test DB directly from models instead of running all migration files
# --reuse-db: Reuses the test DB across runs to save startup time (unless schema changes)
addopts = --nomigrations --reuse-db
